languageCode = "es"
languageName = "Spanish"
weight = 1
title = "Vigilias de Adoración y Reparación"

[params]
  displayName = "ES"
  isoCode = "es"
  rtl = false
  logo = "img/logo.png"
  description = "My awesome website"
  # copyright = "Copy, _right?_ :thinking_face:"
  dateFormat = "2 January 2006"

[author]
  name = "FRICYDIM - Puebla"
  image = "img/avatar.webp"
  headline = "Una vigilia de reparación al Sagrado Corazón de Jesús y al Inmaculado Corazón de María es un acto de devoción y oración, generalmente nocturno, en el que los fieles buscan consolar y reparar las ofensas hechas a los corazones de Jesús y María mediante la adoración, el rezo del santo Rosario y otras prácticas espirituales."
  bio = "Una vigilia de reparación al Sagrado Corazón de Jesús y al Inmaculado Corazón de María es un acto de devoción y oración, generalmente nocturno, en el que los fieles buscan consolar y reparar las ofensas hechas a los corazones de Jesús y María mediante la adoración, el rezo del santo Rosario y otras prácticas espirituales"
  # links = [
  #   { link = "https://nunocoracao.github.io/blowfish/" },
  #   { github = "https://github.com/nunocoracao/blowfish" },
  #   { x-twitter = "https://twitter.com/burufugu" }
  # ]
